// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "context"
	model "products-crud/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// ProductRepository is an autogenerated mock type for the ProductRepository type
type ProductRepository struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, pe
func (_m *ProductRepository) Save(ctx context.Context, pe *model.ProductEntity) error {
	ret := _m.Called(ctx, pe)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.ProductEntity) error); ok {
		r0 = rf(ctx, pe)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
